# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: excel_rails 0.4.0 ruby lib

Gem::Specification.new do |s|
  s.name = "excel_rails".freeze
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Aditya Sanghi".freeze]
  s.date = "2023-03-01"
  s.description = "Allows you to program spreadsheets using .rxls views".freeze
  s.email = "asanghi@me.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "excel_rails.gemspec",
    "init.rb",
    "lib/excel_rails.rb",
    "rails/init.rb",
    "test/helper.rb",
    "test/test_excel_rails.rb"
  ]
  s.homepage = "http://github.com/asanghi/excel_rails".freeze
  s.rubygems_version = "3.0.3.1".freeze
  s.summary = "Hook rxls to generate Excel documents in Rails 3".freeze
end

